Modify behavior of patch command to work with make

diff --git a/scripts/patch b/scripts/patch
--- a/scripts/patch
+++ b/scripts/patch
@@ -1,20 +1,89 @@
 #!/bin/bash
-cd $(dirname $0)
+set -e
 
-#Get chart directory from input
-CHARTDIR=$1
+cd $(dirname $0)/..
 
-#Get plugin info from package.jsonm using jq
-echo "Grabbing plugin info from $2"
-CHARTNAME=$(cat $2 | jq ".name" | tr -d '"')
-CHARTVERSION=$(cat $2 | jq ".version" | tr -d '"')
-IMAGEREPO=$3
+if [[ -z ${CHART} ]]; then
+    # Assume that the chart is the main one found in this repository
+    CHART="./charts/ui-plugin-server"
+fi
 
-#Edit Chart information to match plugin using yq
-yq -i eval ".name = \"${CHARTNAME}\"" $CHARTDIR/Chart.yaml
-yq -i eval ".version = \"${CHARTVERSION}\"" $CHARTDIR/Chart.yaml
-yq -i eval ".appVersion = \"${CHARTVERSION}\"" $CHARTDIR/Chart.yaml
-yq -i eval ".image.tag = \"${CHARTVERSION}\"" $CHARTDIR/values.yaml
-yq -i eval ".plugin.version = \"${CHARTVERSION}\"" $CHARTDIR/values.yaml
-yq -i eval ".image.repository = \"${IMAGEREPO}/${CHARTNAME}\"" $CHARTDIR/values.yaml
-yq -i eval ".global.cattle.systemDefaultRegistry = \"${IMAGEREPO}\"" $CHARTDIR/values.yaml
+if ! [[ -d ${CHART} ]]; then
+    echo "${CHART} is not a directory"
+    exit 1
+fi
+
+if ! [[ -f ${CHART}/Chart.yaml ]]; then
+    echo "${CHART} is not a valid Helm chart: could not find Chart.yaml"
+    exit 1
+fi
+
+if ! [[ -f ${CHART}/values.yaml ]]; then
+    echo "${CHART} does not have default values: could not find values.yaml"
+    exit 1
+fi
+
+if [[ -z ${REGISTRY} ]]; then
+    # By default, we assume you are using DockerHub  
+    REGISTRY=""
+fi
+
+# Remove trailing slash if it exists
+REGISTRY=${REGISTRY%/}
+
+if [[ -z ${ORG} ]]; then
+    # By default, we assume this is a plugin hosted by Rancher
+    ORG=rancher
+fi
+
+if [[ -z ${PACKAGE_JSON} ]] && [[ -f plugin/package.json ]]; then
+    PACKAGE_JSON=plugin/package.json
+fi
+
+if [[ -n ${PACKAGE_JSON} ]]; then
+    if ! [[ -f ${PACKAGE_JSON} ]]; then
+        echo "Could not find package.json at path ${PACKAGE_JSON}"
+        exit 1
+    fi
+    if [[ -z ${REPO} ]]; then
+        REPO=$(cat ${PACKAGE_JSON} | jq ".name" | tr -d '"')
+    fi
+    if [[ -z ${TAG} ]]; then
+        TAG=$(cat ${PACKAGE_JSON} | jq ".version" | tr -d '"')
+    fi
+
+    DESCRIPTION=$(cat ${PACKAGE_JSON} | jq ".description" | tr -d '"')
+    ICON=$(cat ${PACKAGE_JSON} | jq ".icon" | tr -d '"')
+    KEYWORDS=$(cat ${PACKAGE_JSON} | jq ".keywords")
+    HOME=$(cat ${PACKAGE_JSON} | jq ".homepage" | tr -d '"')
+fi
+
+if [[ -z ${ORG} ]] || [[ -z ${REPO} ]] || [[ -z ${TAG} ]]; then
+    echo "Usage: [CHART=] [REGISTRY=] [ORG=rancher] PACKAGE_JSON=<package-json-path> REPO=<repo> TAG=<tag> ./scripts/patch <chart>"
+    exit 1
+fi
+
+# Edit Chart information to match plugin using yq
+yq -i eval ".name = \"${REPO}\"" $CHART/Chart.yaml
+yq -i eval ".appVersion = \"${TAG}\"" $CHART/Chart.yaml
+yq -i eval ".version = \"${TAG}\"" $CHART/Chart.yaml
+
+if [[ -n "${DESCRIPTION}" ]]; then
+    yq -i eval ".description = \"${DESCRIPTION}\"" $CHART/Chart.yaml
+fi
+
+if [[ -n "${ICON}" ]]; then
+    yq -i eval ".icon = \"${ICON}\"" $CHART/Chart.yaml
+fi
+
+if [[ -n "${KEYWORDS}" ]]; then
+    yq -i -I2 eval ".keywords = ${KEYWORDS}" $CHART/Chart.yaml
+fi
+
+if [[ -n "${HOME}" ]]; then
+    yq -i eval ".home = \"${HOME}\"" $CHART/Chart.yaml
+fi
+
+yq -i eval ".global.cattle.systemDefaultRegistry = \"${REGISTRY}\"" $CHART/values.yaml
+yq -i eval ".image.repository = \"${ORG}/${REPO}\"" $CHART/values.yaml
+yq -i eval ".image.tag = \"${TAG}\"" $CHART/values.yaml
