Assume that plugin directory is always an npm module and generate version from package.json

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,6 +1,6 @@
 FROM registry.suse.com/bci/bci-base:15.4
 
-RUN zypper -n install nginx
+RUN zypper -n install nginx jq
 
 COPY package/nginx.conf /etc/nginx/nginx.conf
 
@@ -20,6 +20,11 @@ WORKDIR /home/plugin-server/plugin-contents
 
 # Copy in plugin files and generate files.txt statically
 COPY plugin plugin
+
+# Must be an npm package to get version from to populate version.txt
+RUN if ! [[ -f "plugin/package.json" ]]; then echo "ERROR: Could not find package.json in plugin directory" && exit 1; fi
+RUN jq ".version" plugin/package.json | tr -d '"' > version.txt
+
 RUN find plugin -type f > files.txt
 
 ENTRYPOINT ["nginx", "-g", "daemon off;"]
diff --git a/scripts/patch b/scripts/patch
--- a/scripts/patch
+++ b/scripts/patch
@@ -36,30 +36,30 @@ if [[ -z ${ORG} ]]; then
     ORG=rancher
 fi
 
-if [[ -z ${PACKAGE_JSON} ]] && [[ -f plugin/package.json ]]; then
+if [[ -z ${PACKAGE_JSON} ]]; then
     PACKAGE_JSON=plugin/package.json
 fi
 
-if [[ -n ${PACKAGE_JSON} ]]; then
-    if ! [[ -f ${PACKAGE_JSON} ]]; then
-        echo "Could not find package.json at path ${PACKAGE_JSON}"
-        exit 1
-    fi
-    if [[ -z ${REPO} ]]; then
-        REPO=$(cat ${PACKAGE_JSON} | jq ".name" | tr -d '"')
-    fi
-    if [[ -z ${TAG} ]]; then
-        TAG=$(cat ${PACKAGE_JSON} | jq ".version" | tr -d '"')
-    fi
-
-    DESCRIPTION=$(cat ${PACKAGE_JSON} | jq ".description" | tr -d '"')
-    ICON=$(cat ${PACKAGE_JSON} | jq ".icon" | tr -d '"')
-    KEYWORDS=$(cat ${PACKAGE_JSON} | jq ".keywords")
-    HOME=$(cat ${PACKAGE_JSON} | jq ".homepage" | tr -d '"')
+if ! [[ -f ${PACKAGE_JSON} ]]; then
+    echo "Could not find package.json at path ${PACKAGE_JSON}"
+    exit 1
 fi
 
+if [[ -z ${REPO} ]]; then
+    REPO=$(cat ${PACKAGE_JSON} | jq ".name" | tr -d '"')
+fi
+
+if [[ -z ${TAG} ]]; then
+    TAG=$(cat ${PACKAGE_JSON} | jq ".version" | tr -d '"')
+fi
+
+DESCRIPTION=$(cat ${PACKAGE_JSON} | jq ".description" | tr -d '"')
+ICON=$(cat ${PACKAGE_JSON} | jq ".icon" | tr -d '"')
+KEYWORDS=$(cat ${PACKAGE_JSON} | jq ".keywords")
+HOME=$(cat ${PACKAGE_JSON} | jq ".homepage" | tr -d '"')
+
 if [[ -z ${ORG} ]] || [[ -z ${REPO} ]] || [[ -z ${TAG} ]]; then
-    echo "Usage: [CHART=] [REGISTRY=] [ORG=rancher] PACKAGE_JSON=<package-json-path> REPO=<repo> TAG=<tag> ./scripts/patch <chart>"
+    echo "Usage: [CHART=charts/ui-plugin-server] [REGISTRY=""] [ORG=rancher] [REPO=<override-repo>] [TAG=<override-tag>] [PACKAGE_JSON=plugin/package.json] ./scripts/patch <chart>"
     exit 1
 fi
 
